SportsStore/WebUI/Controllers/AdminController.cs
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.WebUI.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private IProductRepository repository;

        public AdminController(IProductRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index()
        {
            return View(repository.Products);
        }

        public ViewResult Edit(int productId)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);
            return View(product);
        }

        [HttpPost]
        public ActionResult Edit(Product product, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    product.ImageMimeType = image.ContentType;
                    product.ImageData = new Byte[image.ContentLength];
                    image.InputStream.Read(product.ImageData, 0, image.ContentLength);
                }

                repository.SaveProduct(product);
                // This is a key/value dictionary similar to the session data and view bag features we 
                // have used previously. The key difference from session data is that temp data is deleted 
                // at the end of the HTTP request.
                TempData["message"] = String.Format("{0} has been saved", product.Name);
                return RedirectToAction("Index");
            }
            else
            {
                // there is something wrong with the data values
                return View(product);
            }
        }

        /// <summary>
        /// The Create method does not render its default view. Instead, it specifies that the Edit view should be
        /// used. It is perfectly acceptable for one action method to use a view that is usually associated with another
        /// view. In this case, we inject a new Product object as the view model so that the Edit view is populated with
        /// empty fields.
        /// </summary>
        /// <returns></returns>
        public ViewResult Create()
        {
            return View("Edit", new Product());
        }

        [HttpPost]
        public ActionResult Delete(Int32 productId)
        {
            Product deletedProduct = repository.DeleteProduct(productId);

            if (deletedProduct != null)
            {
                TempData["message"] = String.Format("{0} was deleted", deletedProduct.Name);
            }

            return RedirectToAction("Index");
        }

        
    }
}

SportsStore/WebUI/Controllers/ProductController.cs
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace SportsStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository repository;
        private Int32 pageSize = 3;

        public Int32 PageSize
        {
            get { return pageSize; }
            set { pageSize = value; }
        }

        public ProductController(IProductRepository productRepository)
        {
            this.repository = productRepository;
        }

        public ViewResult List(String category, Int32 page = 1)
        {
            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = (repository.Products
                .Where(p => category == null || p.Category.Equals(category, StringComparison.OrdinalIgnoreCase))
                .OrderBy(p => p.ProductID)
                .Skip((page - 1) * pageSize)
                .Take(pageSize)),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = String.IsNullOrEmpty(category) ? repository.Products.Count() : repository.Products.Where(p => p.Category == category).Count()
                },
                CurrentCategory = category
            };

            return View(model);
        }

        public FileContentResult GetImage(Int32 productId)
        {
            Product prod = repository.Products.FirstOrDefault(p => p.ProductID == productId);

            if (prod != null)
            {
                return File(prod.ImageData, prod.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

SportsStore/WebUI/Views/Admin/Edit.cshtml
@model SportsStore.Domain.Entities.Product

@{
    ViewBag.Title = "Admin: Edit " + @Model.Name;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Edit @Model.Name</h1>
<!--
    We would usually expect a form to postback to the action that rendered it, 
    and this is what the Html.BeginForm assumes by default when it generates an HTML form.
    However, this does not work for our Create method, because we want the form to be posted back to the
    Edit action so that we can save the newly created product data. To fix this, we can use an overloaded
    version of the Html.BeginForm helper method to specify that the target of the form generated in the Edit
    view is the Edit action method of the Admin controller
-->
<!-- Without the enctype attribute, the browser will transmit only the name of the file and not its content,
    which is no use to us at all. To ensure that the enctype attribute appears, we must use an overload of the
    Html.BeginForm helper method that lets us specify HTML attributes-->
@using (Html.BeginForm("Edit","Admin", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.EditorForModel()
    
    <div class="editor-label">Image</div>
    <div class="editor-field">
        @if (Model.ImageData == null)
        {
            @:None
        }
        else
        {
            <img width="150" height="150" src="@Url.Action("GetImage", "Product", new { Model.ProductID })" />
        }
        <div>Upload new image: <input type="file" name="Image" /></div>
        <!-- You may already be aware that Web browsers will upload files properly only when the HTML form
            element defines an enctype value of multipart/form-data. In other words, for a successful upload, 
            the form element must look like this:-->
    </div>
    
    <input type="submit" value="Save" />
    @Html.ActionLink("Cancel and return to List", "Index")
}

SportsStore/WebUI/Views/Admin/Index.cshtml
@model IEnumerable<SportsStore.Domain.Entities.Product>

@{
    ViewBag.Title = "Admin: All Products";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div>
    <!-- Generating URLs (and Not Links) -->
    You are at: @Url.Action(@ViewBag.Action, @ViewBag.Controller, new { id = "admin" })
</div>

<h1>All Products</h1>

<table class="Grid">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th class="NumericCol">Price</th>
        <th>Actions</th>
    </tr>
    @foreach(var item in Model)
    {
        <tr>
            <td>@item.ProductID</td>
            <td>@Html.ActionLink(item.Name, "Edit", new { item.ProductID})</td>
            <td class="NumericCol">@item.Price.ToString("c")</td>
            <td>
                @using (Html.BeginForm("Delete", "Admin"))
                {
                    @Html.Hidden("ProductID", item.ProductID)
                    <input type="submit" value="Delete" />
                }
            </td>
        </tr>
    }
</table>
<p>@Html.ActionLink("Add a new product", "Create")</p>