SportsStore/WebUI/Controllers/CartController.cs
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace SportsStore.WebUI.Controllers
{
    /// <summary>
    /// When the MVC Framework receives a request that requires, say, the AddToCart method to be invoked, it
    /// begins by looking at the parameters for the action method. It looks at the list of binders available and tries
    /// to find one that can create instances of each parameter type. Our custom binder is asked to create a Cart
    /// object, and it does so by working with the session state feature. Between our binder and the default
    /// binder, the MVC Framework is able to create the set of parameters required to call the action method,
    /// allowing us to refactor the controller so that it has no knowledge of how Cart objects are created when
    /// requests are received.
    /// </summary>
    public class CartController : Controller
    {
        private IProductRepository repository;
        private IOrderProcessor orderProcessor;

        public CartController(IProductRepository repo, IOrderProcessor proc)
        {
            repository = repo;
            orderProcessor = proc;
        }

        public RedirectToRouteResult AddToCart(Cart cart, Int32 productId, String returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);

            if (product != null)
            {
                cart.AddItem(product, 1);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, Int32 productId, String returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productId);

            if (product != null)
            {
                cart.RemoveLine(product);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public ViewResult Index(Cart cart, String returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public PartialViewResult Summary(Cart cart)
        {
            // TODO: verificar porque ao clicar no summary está concatenando o path url de retorno
            return PartialView(cart);
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }

            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }
    }
}

SportsStore/WebUI/Controllers/NavController.cs
using SportsStore.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace SportsStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IProductRepository repository;

        public NavController(IProductRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(String category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<String> categories = repository.Products
            .Select(x => x.Category)
            .Distinct()
            .OrderBy(x => x);

            return PartialView(categories);
        }

    }
}

SportsStore/WebUI/Controllers/ProductController.cs
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace SportsStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository repository;
        private Int32 pageSize = 3;

        public Int32 PageSize
        {
            get { return pageSize; }
            set { pageSize = value; }
        }

        public ProductController(IProductRepository productRepository)
        {
            this.repository = productRepository;
        }

        public ViewResult List(String category, Int32 page = 1)
        {
            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = (repository.Products
                .Where(p => category == null || p.Category.Equals(category, StringComparison.OrdinalIgnoreCase))
                .OrderBy(p => p.ProductID)
                .Skip((page - 1) * pageSize)
                .Take(pageSize)),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = String.IsNullOrEmpty(category) ? repository.Products.Count() : repository.Products.Where(p => p.Category == category).Count()
                },
                CurrentCategory = category
            };

            return View(model);
        }

        public FileContentResult GetImage(Int32 productId)
        {
            Product prod = repository.Products.FirstOrDefault(p => p.ProductID == productId);

            if (prod != null)
            {
                return File(prod.ImageData, prod.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

SportsStore/WebUI/Views/Shared/ProductSummary.cshtml
@model SportsStore.Domain.Entities.Product

<div class="item">
        @if (Model.ImageData != null) {
            <div style="float:left;margin-right:20px">
                <img draggable="false" width="75" height="75" src="@Url.Action("GetImage", "Product", new { Model.ProductID })" />
            </div>
        }
        <h3>@Model.Name</h3>
        Description: @Model.Description

        @using(Html.BeginForm("AddToCart", "Cart")) {
            @Html.HiddenFor(x => x.ProductID)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" value="+ Add to cart" />
    }

        <h4>Price: @Model.Price.ToString("c")</h4>
    </div>

SportsStore/WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<!-- the convention is to start the layout name with an underscore -->
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/Admin.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-1.7.1.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <title></title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="Message">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

SportsStore/WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" type="text/css" rel="stylesheet" />
</head>
<body>
    <div id="header">
        @{Html.RenderAction("Summary", "Cart");}
        <div class="title">SPORTS STORE</div>
    </div>
    <div id="categories">
        <!-- The RenderAction method writes its content directly to the response stream,
     -- just like the RenderPartial method. This means that the method returns void,
     -- and therefore cannot be used with a regular Razor at tag.
     -- Instead, we must enclose the call to the method inside a Razor code block (and remember to terminate the statement with a semicolon).-->

        @{ Html.RenderAction("Menu", "Nav"); }
    </div>
    <div id="content">
        @RenderBody()
    </div>
</body>
</html>